# Generated by Django 3.2.8 on 2021-10-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20211020_1939'),
        ('beans', '0002_auto_20211020_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='roastery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.roastery'),
        ),
    ]
