# Generated by Django 3.2.8 on 2021-10-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20211020_1848'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='OperatingHours',
        ),
    ]
