# Generated by Django 3.2.8 on 2021-10-20 18:38

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(default='', max_length=256, null=True)),
                ('full_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address')),
                ('operating_hours', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operatinghours')),
            ],
            options={
                'verbose_name': 'Roastery',
                'verbose_name_plural': 'Roasteries',
            },
        ),
        migrations.CreateModel(
            name='Distributer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('name', models.CharField(max_length=256)),
                ('full_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address')),
                ('operating_hours', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operatinghours')),
            ],
            options={
                'verbose_name': 'Distributer',
                'verbose_name_plural': 'Distributers',
            },
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(default='', max_length=256, null=True)),
                ('full_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address')),
                ('operating_hours', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operatinghours')),
            ],
            options={
                'verbose_name': 'Cafe',
                'verbose_name_plural': 'Cafes',
            },
        ),
    ]
