# Generated by Django 3.2.8 on 2021-10-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20211020_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='full_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.address'),
        ),
        migrations.AlterField(
            model_name='distributer',
            name='full_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.address'),
        ),
        migrations.AlterField(
            model_name='roastery',
            name='full_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.address'),
        ),
    ]
