# Generated by Django 3.2.8 on 2021-10-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20211020_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='location',
        ),
        migrations.RemoveField(
            model_name='distributer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='roastery',
            name='location',
        ),
        migrations.AddField(
            model_name='cafe',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributer',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributer',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roastery',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roastery',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
