# Generated by Django 3.2.8 on 2021-10-21 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20211020_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Cafe Note',
                'verbose_name_plural': 'Cafe Notes',
            },
        ),
    ]
